import type { Transaction } from "@/lib/schema";
import type { NLQSpecification, NLQOperator } from "@/lib/parse";

/**
 * Executes an NLQ specification against a local list of transactions.
 * @param transactions The user's transactions.
 * @param spec The specification generated by the LLM.
 * @returns The aggregated total and the matching rows.
 */
export function executeNlqSpec(
  transactions: Transaction[],
  spec: NLQSpecification,
): { total: number | null; rows: Transaction[] } {
  let filtered = transactions;

  // 1. Resolve Relative Range (Heuristic)
  // Since we are on the client, we'll use a simple implementation of rangeBounds
  if (spec.range && spec.range !== "all") {
    const now = new Date();
    const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate());

    if (spec.range === "today") {
      filtered = filtered.filter(t => new Date(t.transactedAt) >= startOfDay);
    } else if (spec.range === "yesterday") {
      const yesterday = new Date(startOfDay);
      yesterday.setDate(yesterday.getDate() - 1);
      filtered = filtered.filter(t => {
        const d = new Date(t.transactedAt);
        return d >= yesterday && d < startOfDay;
      });
    } else if (spec.range === "this_month") {
      const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
      filtered = filtered.filter(t => new Date(t.transactedAt) >= monthStart);
    } else if (spec.range === "last_month") {
      const lastMonthStart = new Date(now.getFullYear(), now.getMonth() - 1, 1);
      const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
      filtered = filtered.filter(t => {
        const d = new Date(t.transactedAt);
        return d >= lastMonthStart && d < thisMonthStart;
      });
    }
    // Note: "this_week" omitted for brevity, but can be added.
  }

  // 2. Apply Filters
  for (const f of spec.filters) {
    const { field, operator, value } = f;
    filtered = filtered.filter(t => {
      const val = getFieldValue(t, field);

      switch (operator) {
        case "eq": return val === value;
        case "ilike": return String(val).toLowerCase().includes(String(value).toLowerCase());
        case "gte": return val >= value;
        case "lt": return val < value;
        case "in": return Array.isArray(value) && value.includes(val);
        default: return true;
      }
    });
  }

  // 3. Limit
  if (spec.limit) {
    filtered = filtered.slice(0, spec.limit);
  }

  // 4. Aggregate
  let total: number | null = null;
  const amounts = filtered.map(t => Number(t.amountMinor));

  if (amounts.length === 0) {
    return { total: null, rows: [] };
  }

  switch (spec.aggregate) {
    case "sum":
      total = amounts.reduce((a, b) => a + b, 0);
      break;
    case "count":
      total = amounts.length;
      break;
    case "max":
      total = Math.max(...amounts);
      break;
    case "min":
      total = Math.min(...amounts);
      break;
    case "avg":
      total = Math.round(amounts.reduce((a, b) => a + b, 0) / amounts.length);
      break;
  }

  return { total, rows: filtered };
}

function getFieldValue(t: Transaction, field: string): any {
  switch (field) {
    case "category_id": return t.categoryId;
    case "merchant_canonical": return t.merchantCanonical;
    case "merchant_raw": return t.merchantRaw;
    case "direction": return t.direction;
    case "transacted_at": return t.transactedAt;
    default: return null;
  }
}
